#:schema node_modules/wrangler/config-schema.json
name = "my-next-hono"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB"
database_name = "demo-hono-next-db"
database_id = "2722590c-80fc-40cc-976a-60c4b3f82248"
migrations_dir = "src/server/migrations"