#:schema node_modules/wrangler/config-schema.json
name = "my-next-hono"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB"
database_name = "demo-hono-next-db"
database_id = "" # Set a database ID
migrations_dir = "src/server/migrations"